# Generated by Django 3.2.25 on 2025-11-27 14:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("email", models.EmailField(max_length=254)),
                ("organization", models.CharField(blank=True, max_length=120)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LabExperience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lab_name", models.CharField(max_length=255)),
                ("role", models.CharField(max_length=120)),
                ("start_year", models.PositiveSmallIntegerField()),
                ("end_year", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=120)),
                (
                    "focus",
                    models.CharField(
                        help_text="Key techniques or research focus", max_length=255
                    ),
                ),
                ("description", models.TextField()),
                ("report_link", models.URLField(blank=True)),
            ],
            options={
                "ordering": ["-start_year"],
            },
        ),
        migrations.CreateModel(
            name="NewsPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("summary", models.TextField()),
                ("link", models.URLField(blank=True)),
                ("published_on", models.DateField(default=django.utils.timezone.now)),
                ("is_featured", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-published_on", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "technologies",
                    models.CharField(help_text="Comma-separated list", max_length=255),
                ),
                (
                    "project_type",
                    models.CharField(
                        choices=[
                            ("genomics", "Genomics Pipeline"),
                            ("bioinformatics", "Bioinformatics Tool"),
                            ("modeling", "Modeling & Simulation"),
                            ("data", "Data Resource"),
                        ],
                        default="genomics",
                        max_length=20,
                    ),
                ),
                ("duration", models.CharField(blank=True, max_length=100)),
                ("link", models.URLField(blank=True)),
                ("repository", models.URLField(blank=True)),
                ("published_on", models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["project_type", "title"],
            },
        ),
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("journal", models.CharField(blank=True, max_length=255)),
                ("year", models.PositiveSmallIntegerField()),
                ("topic", models.CharField(max_length=120)),
                ("summary", models.TextField()),
                ("doi_link", models.URLField(blank=True)),
                ("github_link", models.URLField(blank=True)),
                (
                    "external_resource",
                    models.URLField(
                        blank=True, help_text="Link to Google Scholar or similar"
                    ),
                ),
                ("featured", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-year", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("programming", "Programming"),
                            ("bioinformatics", "Bioinformatics Platforms"),
                            ("statistics", "Statistics & Modeling"),
                            ("cloud", "Cloud & DevOps"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "proficiency",
                    models.PositiveSmallIntegerField(help_text="Percentage 0-100"),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                ("example_link", models.URLField(blank=True)),
            ],
            options={
                "ordering": ["category", "-proficiency"],
            },
        ),
    ]
