# Generated by Django 3.2.25 on 2025-11-27 14:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="newspost",
            options={"ordering": ["-publish_at", "-id"]},
        ),
        migrations.RemoveField(
            model_name="newspost",
            name="published_on",
        ),
        migrations.AddField(
            model_name="newspost",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="newspost",
            name="is_draft",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="newspost",
            name="publish_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="newspost",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name="newspost",
            name="unpublish_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="newspost",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
