# Generated by Django 3.2.25 on 2025-11-27 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0002_auto_20251127_1438"),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedFilter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "filter_type",
                    models.CharField(
                        choices=[
                            ("publication", "Publications"),
                            ("project", "Projects"),
                        ],
                        max_length=20,
                    ),
                ),
                ("query", models.CharField(blank=True, max_length=255)),
                ("parameters", models.JSONField(blank=True, default=dict)),
                ("is_public", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
