# Generated by Django 3.2.25 on 2025-11-27 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0004_analyticsdataset"),
    ]

    operations = [
        migrations.CreateModel(
            name="Collaboration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "partner_type",
                    models.CharField(
                        choices=[
                            ("academic", "Academic"),
                            ("clinical", "Clinical"),
                            ("industry", "Industry"),
                            ("ngo", "NGO / Philanthropy"),
                        ],
                        default="academic",
                        max_length=20,
                    ),
                ),
                ("region", models.CharField(max_length=120)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("start_year", models.PositiveSmallIntegerField()),
                ("end_year", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("summary", models.TextField()),
                ("grants", models.CharField(blank=True, max_length=255)),
                ("responsibilities", models.TextField(blank=True)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                (
                    "labs",
                    models.ManyToManyField(
                        blank=True,
                        related_name="collaborations",
                        to="website.LabExperience",
                    ),
                ),
                (
                    "projects",
                    models.ManyToManyField(
                        blank=True, related_name="collaborations", to="website.Project"
                    ),
                ),
            ],
            options={
                "ordering": ["-start_year"],
            },
        ),
    ]
